using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BurstPQS.Generators;

[Generator]
public class StructInheritsGenerator : IIncrementalGenerator
{
    const string AttributeFullName = "BurstPQS.CompilerServices.StructInheritAttribute";

    const string AttributeSource =
        @"// <auto-generated/>
using System;

namespace BurstPQS.CompilerServices
{
    [AttributeUsage(AttributeTargets.Struct, AllowMultiple = false)]
    internal class StructInheritAttribute : Attribute
    {
        public Type BaseType { get; }
        public string Name { get; set; } = ""__base"";

        public StructInheritAttribute(Type baseType)
        {
            BaseType = baseType;
        }
    }
}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("StructInheritAttribute.g.cs", AttributeSource)
        );

        var provider = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is StructDeclarationSyntax,
                transform: static (ctx, _) => GetModel(ctx)
            )
            .Where(static m => m is not null);

        context.RegisterSourceOutput(provider, static (spc, model) => Execute(spc, model!.Value));
    }

    record struct MemberModel(string Code);

    record struct GeneratorModel(
        string Namespace,
        string StructName,
        string Accessibility,
        string FieldName,
        string BaseTypeFullName,
        ImmutableArray<string> ContainingTypes,
        ImmutableArray<MemberModel> Members,
        ImmutableArray<MemberModel> Constructors
    );

    static GeneratorModel? GetModel(GeneratorAttributeSyntaxContext ctx)
    {
        var structSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
        var attr = ctx.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString() == AttributeFullName
        );
        if (attr is null)
            return null;

        // Get base type from constructor arg
        if (
            attr.ConstructorArguments.Length == 0
            || attr.ConstructorArguments[0].Value is not INamedTypeSymbol baseType
        )
            return null;

        // Get field name
        string fieldName = "__base";
        foreach (var named in attr.NamedArguments)
        {
            if (named.Key == "Name" && named.Value.Value is string name)
                fieldName = name;
        }

        // Collect existing members on the struct (to skip)
        var existingMembers = new HashSet<string>();
        foreach (var member in structSymbol.GetMembers())
        {
            if (member is IMethodSymbol method && method.MethodKind == MethodKind.Constructor)
                continue;
            existingMembers.Add(GetMemberSignatureKey(member));
        }

        // Collect base type members to forward
        var members = new List<MemberModel>();
        foreach (var member in baseType.GetMembers())
        {
            if (member.IsStatic)
                continue;
            if (member.DeclaredAccessibility != Accessibility.Public)
                continue;
            if (member is IMethodSymbol m && m.MethodKind == MethodKind.Constructor)
                continue;
            if (member is IMethodSymbol m2 && m2.MethodKind == MethodKind.PropertyGet)
                continue;
            if (member is IMethodSymbol m3 && m3.MethodKind == MethodKind.PropertySet)
                continue;

            string key = GetMemberSignatureKey(member);
            if (existingMembers.Contains(key))
                continue;

            string code = GenerateMemberForwarding(member, fieldName);
            if (code is not null)
                members.Add(new MemberModel(code));
        }

        // Check if the struct has any user-declared constructors
        var hasUserConstructors = structSymbol
            .GetMembers()
            .Any(m =>
                m is IMethodSymbol { MethodKind: MethodKind.Constructor } ctor
                && !ctor.IsImplicitlyDeclared
            );

        // Forward base type constructors if no user constructors exist
        var constructors = new List<MemberModel>();
        if (!hasUserConstructors)
        {
            foreach (var member in baseType.GetMembers())
            {
                if (
                    member is IMethodSymbol { MethodKind: MethodKind.Constructor } ctor
                    && !ctor.IsImplicitlyDeclared
                    && ctor.DeclaredAccessibility == Accessibility.Public
                )
                {
                    var code = GenerateConstructorForwarding(ctor, fieldName, structSymbol.Name);
                    if (code is not null)
                        constructors.Add(new MemberModel(code));
                }
            }
        }

        // Gather containing types for nesting
        var containingTypes = ImmutableArray.CreateBuilder<string>();
        var parent = structSymbol.ContainingType;
        while (parent is not null)
        {
            var parentKeyword = parent.IsValueType ? "struct" : "class";
            var parentStatic = parent.IsStatic ? "static " : "";
            var parentPartial = "partial ";
            var parentAccessibility = SyntaxFacts.GetText(parent.DeclaredAccessibility);
            containingTypes.Add(
                $"{parentAccessibility} {parentStatic}{parentPartial}{parentKeyword} {parent.Name}"
            );
            parent = parent.ContainingType;
        }
        containingTypes.Reverse();

        var ns =
            structSymbol.ContainingNamespace?.IsGlobalNamespace == true
                ? null
                : structSymbol.ContainingNamespace?.ToDisplayString();

        var accessibility = SyntaxFacts.GetText(structSymbol.DeclaredAccessibility);

        return new GeneratorModel(
            ns,
            structSymbol.Name,
            accessibility,
            fieldName,
            baseType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            containingTypes.ToImmutable(),
            members.Select(m => m).ToImmutableArray(),
            constructors.Select(m => m).ToImmutableArray()
        );
    }

    static string GetMemberSignatureKey(ISymbol member)
    {
        if (member is IMethodSymbol method)
        {
            var paramTypes = string.Join(
                ",",
                method.Parameters.Select(p =>
                    p.RefKind.ToString()
                    + ":"
                    + p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                )
            );
            return $"M:{method.Name}({paramTypes})";
        }
        if (member is IPropertySymbol prop)
            return $"P:{prop.Name}";
        if (member is IFieldSymbol field)
            return $"F:{field.Name}";
        return member.Name;
    }

    static string GenerateMemberForwarding(ISymbol member, string fieldName)
    {
        if (member is IFieldSymbol field)
            return GenerateFieldForwarding(field, fieldName);
        if (member is IPropertySymbol prop)
            return GeneratePropertyForwarding(prop, fieldName);
        if (member is IMethodSymbol method)
            return GenerateMethodForwarding(method, fieldName);
        return null;
    }

    static string GenerateFieldForwarding(IFieldSymbol field, string fieldName)
    {
        var type = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var name = field.Name;

        if (field.IsReadOnly)
        {
            return $@"        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public readonly {type} {name} => {fieldName}.{name};";
        }
        else
        {
            return $@"        public {type} {name}
        {{
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            readonly get => {fieldName}.{name};
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            set => {fieldName}.{name} = value;
        }}";
        }
    }

    static string GeneratePropertyForwarding(IPropertySymbol prop, string fieldName)
    {
        var type = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var name = prop.Name;

        bool hasGetter = prop.GetMethod is not null;
        bool hasSetter = prop.SetMethod is not null;
        bool isReadonly =
            (prop.GetMethod?.IsReadOnly ?? false)
            || (!hasSetter && (prop.GetMethod?.IsReadOnly ?? true));

        if (hasGetter && !hasSetter)
        {
            var readonlyMod = isReadonly ? "readonly " : "";
            return $"        public {readonlyMod}{type} {name} => {fieldName}.{name};";
        }
        else if (hasGetter && hasSetter)
        {
            var getReadonly = (prop.GetMethod?.IsReadOnly ?? false) ? "readonly " : "";
            return $@"        public {type} {name}
        {{
            {getReadonly}get => {fieldName}.{name};
            set => {fieldName}.{name} = value;
        }}";
        }
        else if (hasSetter)
        {
            return $@"        public {type} {name}
        {{
            set => {fieldName}.{name} = value;
        }}";
        }

        return null;
    }

    static string GenerateMethodForwarding(IMethodSymbol method, string fieldName)
    {
        var returnType = method.ReturnsVoid
            ? "void"
            : method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var readonlyMod = method.IsReadOnly ? "readonly " : "";

        var refReturn = "";
        if (method.ReturnsByRef)
            refReturn = "ref ";
        else if (method.ReturnsByRefReadonly)
            refReturn = "ref readonly ";

        // Build parameter list
        var paramList = new StringBuilder();
        var argList = new StringBuilder();
        for (int i = 0; i < method.Parameters.Length; i++)
        {
            if (i > 0)
            {
                paramList.Append(", ");
                argList.Append(", ");
            }

            var p = method.Parameters[i];
            var paramType = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            string refKindKeyword = "";
            string argRefKind = "";
            switch (p.RefKind)
            {
                case RefKind.Ref:
                    refKindKeyword = "ref ";
                    argRefKind = "ref ";
                    break;
                case RefKind.Out:
                    refKindKeyword = "out ";
                    argRefKind = "out ";
                    break;
                case RefKind.In:
                    refKindKeyword = "in ";
                    argRefKind = "in ";
                    break;
            }

            if (p.IsParams)
                refKindKeyword = "params " + refKindKeyword;

            paramList.Append($"{refKindKeyword}{paramType} {p.Name}");
            argList.Append($"{argRefKind}{p.Name}");
        }

        var call = method.ReturnsVoid
            ? $"{fieldName}.{method.Name}({argList})"
            : $"{refReturn}{fieldName}.{method.Name}({argList})";

        return $"        public {readonlyMod}{refReturn}{returnType} {method.Name}({paramList}) => {call};";
    }

    static string GenerateConstructorForwarding(
        IMethodSymbol ctor,
        string fieldName,
        string structName
    )
    {
        var paramList = new StringBuilder();
        var argList = new StringBuilder();
        for (int i = 0; i < ctor.Parameters.Length; i++)
        {
            if (i > 0)
            {
                paramList.Append(", ");
                argList.Append(", ");
            }

            var p = ctor.Parameters[i];
            var paramType = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            string refKindKeyword = "";
            string argRefKind = "";
            switch (p.RefKind)
            {
                case RefKind.Ref:
                    refKindKeyword = "ref ";
                    argRefKind = "ref ";
                    break;
                case RefKind.Out:
                    refKindKeyword = "out ";
                    argRefKind = "out ";
                    break;
                case RefKind.In:
                    refKindKeyword = "in ";
                    argRefKind = "in ";
                    break;
            }

            paramList.Append($"{refKindKeyword}{paramType} {p.Name}");
            argList.Append($"{argRefKind}{p.Name}");
        }

        return $"        public {structName}({paramList}) => {fieldName} = new({argList});";
    }

    static void Execute(SourceProductionContext context, GeneratorModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
        }

        // Open containing types
        foreach (var ct in model.ContainingTypes)
        {
            sb.AppendLine($"    {ct}");
            sb.AppendLine("    {");
        }

        var indent = model.ContainingTypes.Length > 0 ? "        " : "    ";
        sb.AppendLine($"{indent}{model.Accessibility} partial struct {model.StructName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    {model.BaseTypeFullName} {model.FieldName};");

        foreach (var ctor in model.Constructors)
        {
            sb.AppendLine();
            if (model.ContainingTypes.Length > 0)
            {
                foreach (var line in ctor.Code.Split('\n'))
                    sb.AppendLine("    " + line.TrimEnd('\r'));
            }
            else
            {
                sb.AppendLine(ctor.Code);
            }
        }

        foreach (var member in model.Members)
        {
            sb.AppendLine();
            if (model.ContainingTypes.Length > 0)
            {
                // Extra indent for nested types
                foreach (var line in member.Code.Split('\n'))
                    sb.AppendLine("    " + line.TrimEnd('\r'));
            }
            else
            {
                sb.AppendLine(member.Code);
            }
        }

        sb.AppendLine($"{indent}}}");

        // Close containing types
        foreach (var _ in model.ContainingTypes)
        {
            sb.AppendLine("    }");
        }

        if (model.Namespace is not null)
            sb.AppendLine("}");

        var hintName =
            model.ContainingTypes.Length > 0
                ? $"{string.Join(".", model.ContainingTypes.Select(ct => ct.Split(' ').Last()))}.{model.StructName}.g.cs"
                : $"{model.StructName}.g.cs";

        context.AddSource(hintName, sb.ToString());
    }
}
